### ISSUE TITLE
Image issues

### ISSUE THREAD

**Issue by FliesWithCrows** [lifelike/countersheetsextension#74] opened 2021-04-22 09:31 UTC
A couple of issues with how the extension seems to be handling images: 

1) Sometimes, when attempting to pull an image, rather than importing the .png listed in the specified .csv, it looks for 'g4274.png' in the unzipped countersheet templates folder - almost like its ignoring the image path?

2) static images (eg for background or textures etc) disappear and are either replaced by: 

-  the 'image not found' picture.   
-  a png listed in the csv file.

examples below - card x becomes card y
[card-x](https://user-images.githubusercontent.com/82773614/115691236-c6ee8480-a355-11eb-878c-f02e026671ba.png)

[card-y](https://user-images.githubusercontent.com/82773614/115691289-d241b000-a355-11eb-8698-db57681debef.png)

**Comment by lifelike** [comment] 2021-04-24 08:03
1. Did you set the Image Path option in the dialog correctly?

If you right-click images and check their Image Properties you can see what the path is they use, and compare that to what you expected it to be.

2. My only guess is that relative paths are used for those images (again, this can be checked in Image Properties). So you have a template.svg and in the same folder a background.png, but the generated sheet svg is somewhere else. This happens easily for instance when generating PNGs or PDFs if you do that in a folder where the original images do not exist. Inkscape can not know how to find background.png from a file that is somewhere else. The fix if this is the case is to either make sure you are in a folder where background.png exists or to change the image path to be the full absolute path (e.g. "c:\users\me\pictures\background.png" or something like that) so that it does not matter if the svg file moves around. Or embed the image in the svg (but that makes the file bigger).

**Comment by ernierasta** [comment] 2021-07-13 21:04
@FliesWithCrows I think I have similar issues as you. And have them solved partially. Will send PR hopefully in few days.

**Comment by FliesWithCrows** [comment] 2021-07-14 19:06
Good luck. I gave up and replaced all my static graphics with dynamic which is a massive pain but it works...

**Comment by ernierasta** [comment] 2021-07-15 05:12
Ohh, it is really easy to fix, sorry I wasn't quicker. I will send PR today. Funny thing is, that I think both types of images may have problems. My PR will fix embedded, but I think sometimes linked images may also be problematic. If I will be able to replicate it I will send separate PR also for linked ones.

**Comment by lifelike** [comment] 2021-07-27 12:30
Was there any other image problem here other than what the PR fixed? (Thanks for that btw!)

**Comment by ernierasta** [comment] 2021-07-27 19:41
I am not sure. I am on vacations currently, but I think I saw problem, where path was added to href, but org image path already contained some dirs ... But it maybe was my fault.
Anyway, I will send PR or at least info if I will be able to replicate that. If not, I will also post here, that it seems to be ok.

**Comment by FliesWithCrows** [comment] 2021-08-04 16:52
Yep this has resolved the static / dynamic image issue. Thank you! A small fix has made a big difference! 

The only other issue i had was that i used to get a load of error messages saying that image g4274 in the templates folder was not valid. I have no idea why it was trying to import that image or event looking in the templates folder as it wasn't in my csv, but the problem was resolved by deleting the countersheet templates folder(?!)

**Comment by ernierasta** [comment] 2021-09-22 17:41
Hi guys!
I found it! I knew, there is some other kind of mess with images, but I couldn't reproduce it.

When you have linked image (in my case **svg**) in component template and you do not replace it (it is the same on all generated components) - image will have wrong **xlink:href**. 

Here is example how it looks:
`/home/user/somedir/images/file:///home/user/somedir/images/broadsword.svg`
I think we are adding path even where there is full path given. I did not yet looked at code, but I will be back with PR. ;-)

**Comment by ernierasta** [comment] 2021-09-22 18:44
It seems it can be fixed just by changing from:
`os.path.join(self.imagedir, filename)`
to:
`os.path.join(self.imagedir, os.path.basename(filename))`

But question is, if we are OK with absolute path there. But I will not go into this discussion now, as it seems we can generally improve absolute/relative path attributes.

**Comment by lifelike** [comment] 2021-09-22 19:04
That fix looks wrong, as someone could use a valid filename like "images/some.png" for a relative path vs the imagedir.

By "you do not replace" do you mean that the image is not mentioned in the CSV at all? I think the correct thing to do would be to detect that the path is already absolute and not modify it at all? If you put file:///home/user/somedir/images/broadsword.svg in your template you presumably want that exact image to be used, and not some other broadsword.svg relative to some other path? If you wanted that you could just change the template, or use the CSV to modify it.

**Comment by ernierasta** [comment] 2021-09-22 20:43
Hi Pelle :-)
You are right, it would be definitely more logical. 

BTW: from my testing it unfortunately currently impossible to use relative path. It is probably related to change in inx file (related to new type="folder" from Inkscape 1.0). 

It seems that absolute path is always returned even if you enter there f.e:
`images`
Python will receive:
`/path/to/inkscape/extensions/images`

I know how to solve it probably, but something is messing relative href further. Currently investigating.

**Closed** 2022-05-01 11:06 UTC
